"""
Module 8 — Notifications
Trigger-based in-app alerts displayed on the dashboard.
Triggers: low stock (prioritized by ABC class), system warnings, backups.
ABC priority: Class A items trigger alerts at higher thresholds.
"""
from django.db import models
from django.conf import settings
from django.utils import timezone


class Notification(models.Model):
    """
    In-app notification record.
    Displayed as dashboard alerts. Auto-generated by system triggers.
    """
    TYPE_CHOICES = [
        ('low_stock',      'Low Stock Alert'),
        ('out_of_stock',   'Out of Stock Alert'),
        ('system_warning', 'System Warning'),
        ('backup_reminder','Backup Reminder'),
        ('backup_success', 'Backup Success'),
        ('restore_success','Restore Success'),
        ('info',           'Information'),
    ]

    PRIORITY_CHOICES = [
        ('critical', 'Critical'),   # Class A low-stock, out-of-stock
        ('high',     'High'),       # Class B low-stock
        ('medium',   'Medium'),     # Class C low-stock, system warnings
        ('low',      'Low'),        # Info, reminders
    ]

    user          = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        null=True, blank=True,      # null = broadcast to all users
        related_name='notifications'
    )
    notification_type = models.CharField(max_length=20, choices=TYPE_CHOICES)
    priority      = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default='medium')
    title         = models.CharField(max_length=200)
    message       = models.TextField()
    source_table  = models.CharField(max_length=50, blank=True)   # e.g. 'inventory'
    source_id     = models.CharField(max_length=50, blank=True)   # ID of triggering record
    is_read       = models.BooleanField(default=False)
    date_created  = models.DateTimeField(default=timezone.now)
    date_read     = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'notifications'
        ordering = ['-date_created']
        indexes  = [
            models.Index(fields=['user', 'is_read']),
            models.Index(fields=['notification_type']),
        ]

    def __str__(self):
        return f'[{self.get_priority_display()}] {self.title}'

    def mark_as_read(self):
        if not self.is_read:
            self.is_read   = True
            self.date_read = timezone.now()
            self.save(update_fields=['is_read', 'date_read'])
