# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales_summary', 'Sales Summary'), ('sales_daily', 'Daily Sales Report'), ('sales_weekly', 'Weekly Sales Report'), ('sales_monthly', 'Monthly Sales Report'), ('sales_annual', 'Annual Sales Report'), ('inventory', 'Inventory Report'), ('low_stock', 'Low Stock Report'), ('abc_analysis', 'ABC Analysis Report'), ('financial', 'Financial Overview'), ('purchase', 'Purchase Report')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Range')], default='daily', max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('source_table', models.CharField(blank=True, max_length=50)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-date_generated'],
            },
        ),
    ]
