# Generated by Django 6.0.4 on 2026-05-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_analytics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Utility', 'Utility (Kuryente, Tubig, Internet)'), ('Payroll', 'Payroll / Sweldo'), ('Rent', 'Rent / Upa'), ('Logistics', 'Delivery / Gasolina'), ('Supplies', 'Store Supplies'), ('Others', 'Others')], default='Others', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
