# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial — Some rows failed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_details', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'csv_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('scan', 'Barcode Scan'), ('csv', 'CSV Import'), ('generated', 'System Generated Barcode')], default='manual', max_length=15)),
                ('barcode_value', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'product_registration_logs',
                'ordering': ['-registered_at'],
            },
        ),
    ]
