# Generated by Django 6.0.4 on 2026-05-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Wallet', 'Online Wallet')], default='Cash', max_length=20),
        ),
    ]
