# Generated by Django 6.0.4 on 2026-05-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0004_alter_transactionitem_transaction_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
