# Generated by Django 6.0.4 on 2026-05-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0003_customer_invoice_invoicepayment'),
        ('point_of_sale', '0005_transaction_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing_payment.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Wallet', 'Online Wallet'), ('credit', 'Trade Credit')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('credit', 'On Credit'), ('voided', 'Voided')], default='open', max_length=10),
        ),
    ]
