# Generated by Django 5.2.13 on 2026-05-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0006_transaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('quotation', 'Quotation'), ('completed', 'Completed'), ('credit', 'On Credit'), ('voided', 'Voided')], default='open', max_length=15),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
