# Generated by Django 5.2.13 on 2026-06-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0007_alter_transaction_status_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
    ]
