# Generated by Django 5.2.13 on 2026-06-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_sale', '0008_remove_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Wallet', 'Online Wallet'), ('credit', 'Trade Credit')], default='Cash', max_length=20),
        ),
    ]
