# Generated by Django 6.0.4 on 2026-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0006_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
