# Generated by Django 5.2.13 on 2026-06-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_payment', '0007_invoice_interest_amount'),
        ('point_of_sale', '0008_remove_transaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='product',
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='transaction_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_records', to='point_of_sale.transactionitem'),
        ),
    ]
