# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('barcode_id', models.CharField(max_length=50, unique=True)),
                ('barcode_generated', models.BooleanField(default=False)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=10)),
                ('abc_classification', models.CharField(choices=[('A', 'Class A — High Value'), ('B', 'Class B — Medium Value'), ('C', 'Class C — Low Value'), ('U', 'Unclassified')], default='U', max_length=1)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('delivery', 'Supplier Delivery'), ('damage', 'Damaged Goods'), ('shrinkage', 'Shrinkage / Loss'), ('correction', 'Stock Correction'), ('return', 'Customer Return'), ('other', 'Other')], max_length=20)),
                ('quantity_before', models.IntegerField()),
                ('quantity_change', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('date_adjusted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stock_adjustments',
                'ordering': ['-date_adjusted'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
    ]
