# Generated by Django 6.0.4 on 2026-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prefix',
            field=models.CharField(default='GEN', help_text='2-5 letter code for IDs', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
