# Generated by Django 6.0.4 on 2026-05-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_prefix_alter_inventoryitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
