# Generated by Django 6.0.4 on 2026-05-07 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_supplier_id_alter_supplier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='item',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_product_58b6bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_barcode_df4768_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_item_na_084c23_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inventory_abc_cla_3f65be_idx',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='annual_demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='abc_classification',
            field=models.CharField(choices=[('A', 'Class A — High Value (70%)'), ('B', 'Class B — Medium Value (20%)'), ('C', 'Class C — Low Value (10%)'), ('U', 'Unclassified')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='min_stock',
        ),
    ]
