# Generated by Django 6.0.4 on 2026-05-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stockadjustment_adjusted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='barcode_generated',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='barcode_image',
        ),
    ]
