# Generated by Django 6.0.4 on 2026-05-07 13:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryitem_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='actual_sales_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manual_annual_demand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
