# Generated by Django 6.0.4 on 2026-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
