# Generated by Django 6.0.4 on 2026-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_supplier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='average_daily_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average items sold per day', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='average_lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='Average days for supplier to deliver'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_daily_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Highest number of items sold in a single day', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='max_lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='Maximum days it took for a delivery to arrive'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='safety_stock',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
