# Generated by Django 6.0.4 on 2026-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_average_daily_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_lead_time_days',
            field=models.PositiveIntegerField(default=7, help_text='Standard days to deliver'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='max_lead_time_days',
            field=models.PositiveIntegerField(default=14, help_text='Maximum expected delay'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='average_lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text="Leave as 0 to use Supplier's default"),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='max_lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text="Leave as 0 to use Supplier's maximum"),
        ),
    ]
