# Generated by Django 6.0.4 on 2026-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplier_default_lead_time_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generated_barcodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
