# Generated by Django 5.2.13 on 2026-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_generatedbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedbarcode',
            name='batch_id',
            field=models.CharField(default='MANUAL', max_length=50),
        ),
    ]
