# Generated by Django 5.2.13 on 2026-06-13 11:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_generatedbarcode_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'product_batches',
                'ordering': ['date_received'],
            },
        ),
    ]
