# Generated by Django 6.0.4 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['expiry_date', 'date_received']},
        ),
        migrations.AddField(
            model_name='productbatch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired'), ('pulled_out', 'Pulled Out/Disposed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
