# Generated by Django 5.2.13 on 2026-06-16 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_productbatch_options_productbatch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedbarcode',
            name='barcode_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be exactly 13 digits long and contain only numbers.', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='barcode_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be exactly 13 digits long and contain only numbers (EAN-13 standard).', regex='^\\d{13}$')]),
        ),
    ]
