# Generated by Django 6.0.4 on 2026-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_user_options_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='reports_access_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='reports_access_requested',
            field=models.BooleanField(default=False),
        ),
    ]
