# Generated by Django 6.0.4 on 2026-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_employeeprofile_reports_access_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='reports_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
