# Generated by Django 6.0.4 on 2026-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_employeeprofile_reports_access_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='settings_access_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='settings_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='settings_access_requested',
            field=models.BooleanField(default=False),
        ),
    ]
