# Generated by Django 6.0.4 on 2026-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_employeeprofile_settings_access_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='billing_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='inventory_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='product_reg_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
