# Generated by Django 6.0.4 on 2026-06-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_employeeprofile_billing_access_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='billing_access_expires_at',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='inventory_access_expires_at',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='product_reg_access_expires_at',
        ),
    ]
