# Generated by Django 6.0.4 on 2026-06-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_employeeprofile_dashboard_access_approved_and_more'),
        ('security', '0007_remove_employeeprofile_billing_access_expires_at_and_more'),
    ]

    operations = [
    ]
