# Generated by Django 6.0.4 on 2026-06-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_merge_20260614_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_delete_product',
            field=models.BooleanField(default=False, verbose_name='Can Delete Product'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_edit_product',
            field=models.BooleanField(default=False, verbose_name='Can Edit Product'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_import_csv',
            field=models.BooleanField(default=False, verbose_name='Can Import CSV'),
        ),
    ]
