# Generated by Django 6.0.4 on 2026-06-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_employeeprofile_can_delete_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='can_delete_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='can_edit_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='can_import_csv',
            field=models.BooleanField(default=False),
        ),
    ]
