# Generated by Django 6.0.4 on 2026-06-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_employeeprofile_can_add_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_add_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_receive_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_view_ledger',
            field=models.BooleanField(default=False),
        ),
    ]
