# Generated by Django 6.0.4 on 2026-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0012_employeeprofile_can_add_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_add_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_archive_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_edit_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='can_restore_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
