# Generated by Django 6.0.4 on 2026-06-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0013_employeeprofile_can_add_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_add_product',
            field=models.BooleanField(default=False),
        ),
    ]
