# Generated by Django 5.2.13 on 2026-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_employeeprofile_can_add_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='recovery_key',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
