import os
import pyAesCrypt
from datetime import datetime
from django.shortcuts import render, redirect
from django.db import connection
from django.contrib import messages
from django.http import FileResponse
from django.core.management import call_command
from django.conf import settings
from django.core.files.storage import FileSystemStorage

# 🟢 FIX: Gumamit ng get_user_model() para sa Custom User Models
from django.contrib.auth import get_user_model
User = get_user_model()

# 🟢 SIGURADUHING NAKA-IMPORT ITO
from activity_log.utils import log_system_activity
BUFFER_SIZE = 64 * 1024

# ==========================================
# HELPER FUNCTIONS
# ==========================================

def get_current_db_size():
    with connection.cursor() as cursor:
        cursor.execute("SELECT round(sum(data_length + index_length) / 1024 / 1024, 2) FROM information_schema.tables WHERE table_schema = 'jbson_dev';")
        result = cursor.fetchone()
        return result[0] if result and result[0] else 0

def get_last_backup_time():
    backup_dir = os.path.join(settings.BASE_DIR, 'secure_backups')
    if not os.path.exists(backup_dir):
        return "No backups yet"
    
    files = [os.path.join(backup_dir, f) for f in os.listdir(backup_dir) if f.endswith(('.gz', '.sqlite3', '.sql', '.enc'))]
    if not files:
        return "No backups yet"
        
    latest_file = max(files, key=os.path.getctime)
    dt_object = datetime.fromtimestamp(os.path.getctime(latest_file))
    return dt_object.strftime("%B %d, %Y - %I:%M %p")

# Main View
def maintenance_dashboard(request):
    report = []
    tables_to_optimize = [] 
    
    just_optimized = request.session.get('db_optimized_recently', False)

    if not just_optimized:
        with connection.cursor() as cursor:
            cursor.execute("SHOW TABLE STATUS WHERE Data_free > 0")
            tables = cursor.fetchall()
            for table in tables:
                table_name = table[0]
                raw_overhead = table[9] if table[9] is not None else 0
                overhead_mb = round(raw_overhead / 1024 / 1024, 3)
                
                if overhead_mb > 0:
                    tables_to_optimize.append(table_name)
                    report.append(f"Some old records in '{table_name}' are taking up {overhead_mb} MB of extra space.")

    if request.method == "POST":
        if tables_to_optimize: 
            with connection.cursor() as cursor:
                tables_str = ", ".join(tables_to_optimize)
                cursor.execute(f"OPTIMIZE TABLE {tables_str}")
            
            log_system_activity(
                user=request.user,
                action="SYSTEM MAINTENANCE",
                description=f"Cleaned up and optimized storage for: {tables_str}."
            )
            
            request.session['db_optimized_recently'] = True
            messages.success(request, "Storage successfully cleaned and optimized!")
        else:
            request.session['db_optimized_recently'] = True
            messages.info(request, "System is already optimized. No action needed.")
            
        return redirect(request.path)

    context = {
        'db_size': get_current_db_size(),
        'report': report,
        'last_backup_time': get_last_backup_time(),
    }
    
    return render(request, 'dashboard/settings_hub.html', context)


# ==========================================
# BACKUP, RESTORE, AND DELETE VIEWS
# ==========================================

def trigger_backup(request):
    if request.method == 'POST':
        encryption_key = request.POST.get('encryption_key')
        
        if not encryption_key:
            messages.error(request, 'Encryption password is required.')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        try:
            call_command('backup_db')
            
            backup_dir = os.path.join(settings.BASE_DIR, 'secure_backups')
            files = [os.path.join(backup_dir, f) for f in os.listdir(backup_dir) if not f.endswith('.enc')]
            
            if not files:
                raise Exception("No raw backup file was generated by the system.")
                
            latest_file = max(files, key=os.path.getctime)
            encrypted_file = f"{latest_file}.enc"
            
            pyAesCrypt.encryptFile(latest_file, encrypted_file, encryption_key, BUFFER_SIZE)
            
            if os.path.exists(latest_file):
                os.remove(latest_file)
            
            log_system_activity(
                user=request.user,
                action="DATABASE BACKUP",
                description="Successfully generated and downloaded an ENCRYPTED database backup."
            )
            
            response = FileResponse(open(encrypted_file, 'rb'), as_attachment=True)
            return response
            
        except Exception as e:
            messages.error(request, f'Backup failed: {e}')
            return redirect(request.META.get('HTTP_REFERER', '/'))


def trigger_restore(request):
    if request.method == 'POST' and request.FILES.get('backup_file'):
        decryption_key = request.POST.get('decryption_key')
        uploaded_file = request.FILES['backup_file']
        
        if not decryption_key:
            messages.error(request, 'Decryption password is required.')
            return redirect(request.META.get('HTTP_REFERER', '/'))

        fs = FileSystemStorage(location=os.path.join(settings.BASE_DIR, 'secure_backups'))
        filename = fs.save(uploaded_file.name, uploaded_file)
        encrypted_filepath = fs.path(filename)
        
        decrypted_filepath = encrypted_filepath.replace('.enc', '') if encrypted_filepath.endswith('.enc') else f"{encrypted_filepath}_decrypted.gz"

        try:
            try:
                pyAesCrypt.decryptFile(encrypted_filepath, decrypted_filepath, decryption_key, BUFFER_SIZE)
            except ValueError:
                raise Exception("Incorrect decryption password or corrupted backup file.")

            # 🟢 PROTECT JBSON ACCOUNT: Safely check existing attributes
            jbson_data = None
            try:
                # Ginamit natin ang iexact para case-insensitive
                jbson_user = User.objects.get(username__iexact='jbson') 
                jbson_data = {'password': jbson_user.password}
                
                # Kukunin lang ang mga ito KUNG nag-eexist sa Custom User Model mo
                if hasattr(jbson_user, 'email'):
                    jbson_data['email'] = jbson_user.email
                if hasattr(jbson_user, 'is_superuser'):
                    jbson_data['is_superuser'] = jbson_user.is_superuser
                if hasattr(jbson_user, 'is_staff'):
                    jbson_data['is_staff'] = jbson_user.is_staff
            except User.DoesNotExist:
                pass

            # Restore using the decrypted file
            call_command('restore_db', decrypted_filepath)
            
            # 🟢 RESTORE JBSON ACCOUNT: Ibalik lang ang mga fields na meron ka
            if jbson_data:
                user_obj, created = User.objects.get_or_create(username='JBSON')
                user_obj.password = jbson_data['password']
                
                if 'email' in jbson_data:
                    user_obj.email = jbson_data['email']
                if 'is_superuser' in jbson_data:
                    user_obj.is_superuser = jbson_data['is_superuser']
                if 'is_staff' in jbson_data:
                    user_obj.is_staff = jbson_data['is_staff']
                    
                user_obj.save()
            
            log_system_activity(
                user=request.user,
                action="DATABASE RESTORE",
                description=f"Restored the database using encrypted backup file: '{uploaded_file.name}'."
            )
            
            messages.success(request, 'System successfully restored from encrypted backup!')
            
        except Exception as e:
            messages.error(request, f'Restore failed: {e}')
            
        finally:
            # CLEANUP
            if os.path.exists(encrypted_filepath):
                os.remove(encrypted_filepath)
            if os.path.exists(decrypted_filepath):
                os.remove(decrypted_filepath)
                
        return redirect(request.META.get('HTTP_REFERER', '/'))


def delete_all_data(request):
    if request.method == 'POST':
        # 🟢 FIX: In-update ang listahan para sa Custom User Model ('security_user')
        protected_tables = [
            'security_user', 
            'security_user_groups', 
            'security_user_user_permissions',
            'auth_group', 
            'auth_permission', 
            'django_migrations',
            'django_content_type',
            'django_session',
            'django_admin_log'
        ]

        try:
            with connection.cursor() as cursor:
                cursor.execute("SHOW TABLES")
                all_tables = [row[0] for row in cursor.fetchall()]

                cursor.execute("SET FOREIGN_KEY_CHECKS = 0;")
                
                for table in all_tables:
                    if table not in protected_tables:
                        cursor.execute(f"TRUNCATE TABLE {table};")
                
                cursor.execute("SET FOREIGN_KEY_CHECKS = 1;")

            # Ligtas na ide-delete lahat maliban sa JBSON account gamit ang tamang model
            User.objects.exclude(username__iexact='jbson').delete()

            log_system_activity(
                user=request.user,
                action="SYSTEM WIPE",
                description="Performed a full system wipe. All transactions and extra accounts were cleared."
            )

            messages.success(request, 'System wiped! All transactions and other accounts cleared, but JBSON account remains safe.')
        except Exception as e:
            messages.error(request, f'Error: {e}')
             
    return redirect(request.META.get('HTTP_REFERER', '/'))