# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=200)),
                ('result_table', models.CharField(blank=True, max_length=50)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('date_searched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'search_logs',
                'ordering': ['-date_searched'],
            },
        ),
    ]
