# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query_text'], name='search_logs_query_t_7ee78f_idx'),
        ),
    ]
