# Generated by Django 6.0.4 on 2026-04-29 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_failed', 'Failed Login Attempt'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deactivated', 'User Deactivated'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_deleted', 'Item Deleted'), ('stock_adjusted', 'Stock Adjusted'), ('barcode_generated', 'Barcode Generated'), ('transaction_started', 'Transaction Started'), ('transaction_completed', 'Transaction Completed'), ('transaction_voided', 'Transaction Voided'), ('payment_processed', 'Payment Processed'), ('receipt_generated', 'Receipt Generated'), ('report_generated', 'Report Generated'), ('backup_created', 'Backup Created'), ('restore_performed', 'Restore Performed'), ('csv_imported', 'CSV Imported')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_table', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-date_created'],
            },
        ),
    ]
