# Generated by Django 5.2.13 on 2026-05-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
