# Generated by Django 6.0.4 on 2026-05-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('system_warning', 'System Warning'), ('backup_reminder', 'Backup Reminder'), ('backup_success', 'Backup Success'), ('restore_success', 'Restore Success'), ('info', 'Information'), ('po_arriving', 'PO Arriving Today'), ('po_overdue', 'PO Overdue - Contact Supplier'), ('po_draft_suggested', 'Draft PO Suggested')], max_length=20),
        ),
    ]
