# Generated by Django 6.0.4 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('system_warning', 'System Warning'), ('backup_reminder', 'Backup Reminder'), ('backup_success', 'Backup Success'), ('restore_success', 'Restore Success'), ('info', 'Information')], max_length=20),
        ),
    ]
