# Generated by Django 6.0.4 on 2026-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert'), ('system_warning', 'System Warning'), ('backup_reminder', 'Backup Reminder'), ('backup_success', 'Backup Success'), ('restore_success', 'Restore Success'), ('info', 'Information'), ('invoice_due', 'Invoice Due Alert'), ('invoice_overdue', 'Invoice Overdue Alert')], max_length=20),
        ),
    ]
